server:
  port: 8085
  tomcat:
    threads:
      max: 25  #最大线程数
    accept-count: 25  #线程达到上限后,允许等待的最大线程数
    max-connections: 100 #最大连接数
#  servlet:
#    context-path: abde


feign:
  sentinel:
    enabled: true

spring:
#  profiles:
#    active: local
  application:
    name: login-service
  config:
    import: "nacos:abde-ms-jdbc,nacos:abde-ms-log"
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
    openfeign:
      okhttp:
        enabled: true
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml

